### ISSUE TITLE
Rename project to gpu-driver-container

### ISSUE THREAD

**Issue by ArangoGutierrez** [NVIDIA/gpu-driver-container#26]
Avoiding uppercase letters in Git repository names is generally a good practice for several reasons:

- Consistency with Git Conventions: Git itself is case-sensitive, meaning that "MyProject" and "myproject" would be considered different repositories. Consistently using lowercase letters aligns with Git's conventions and reduces the likelihood of confusion or errors related to case sensitivity.
- Uniformity in URLs and File Systems: URLs and file systems are often case-sensitive as well, especially in Unix-like systems. Using lowercase letters exclusively ensures consistency in URLs (e.g., when accessing repositories hosted on platforms like GitHub) and file paths, which can prevent issues related to casing discrepancies.
- Readability and Aesthetics: Lowercase letters are generally easier to read and aesthetically pleasing, especially when combined with hyphens or underscores to separate words. This enhances the readability of repository names in command-line interfaces, URLs, and documentation.
- Avoidance of Platform Limitations: Some platforms or services may have limitations or conventions regarding uppercase letters in repository names. By sticking to lowercase letters, you can ensure compatibility with a wide range of platforms and tools without running into unexpected restrictions.

**Comment by cdesiniotis** [comment]
I have renamed the project to `gpu-driver-container` and updated the gitlab mirror.
